name: Deploy our Microservices app

on: 
  push: 
    branches: 
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker build -t ahmedgamil/multi-client ./client
          docker build -t ahmedgamil/multi-server ./server
          docker build -t ahmedgamil/multi-worker ./worker
          docker build -t ahmedgamil/multi-nginx ./nginx

      - name: Push Docker images
        run: |
          docker push ahmedgamil/multi-client
          docker push ahmedgamil/multi-server
          docker push ahmedgamil/multi-worker
          docker push ahmedgamil/multi-nginx
